baseurl = "https://honzajde.github.io/"
title = "Trading Tools"
theme = "zen"
languageCode = "en-us"
copyright = "honzajde"
disqusShortname = "XXX"
googleAnalytics = "XXX"

[Author]
    name = "honzajde"
    profile = "https://google.com/+XXX"

[Taxonomies]
    tag = "tags"

[Params]
    intro = true
    headline = "Trading tools"
    description = "Commandline tools for day traders of US stocks (namely NASDAQ)."
    github = "https://github.com/XXX"
    gitlab = "https://gitlab.com/XXX"
    gplus = "https://google.com/+XXX"
    linkedin = "https://linkedin.com/in/XXX/"
    twitter = "https://twitter.com/XXX"
    stackoverflow = "https://stackoverflow.com/users/XXX/YYY"
    email = "XXX@example.com"
    opengraph = true
    shareTwitter = false
    shareFacebook = false
    shareGooglePlus = false
    shareLinkedIn = false
    dateFormat = "Jan 2, 2006"

[Permalinks]
    post = "/:year/:month/:day/:filename/"

[[menu.main]]
    name = "Home"
    url = "/post/"
    weight = 1

# [[menu.main]]
#     name = "Projects"
#     url = "/project/"
#     weight = 2

# [[menu.main]]
#     name = "Contact"
#     url = "/page/contact/"
#     weight = 3

# [[menu.main]]
#     name = "About"
#     url = "/page/about/"
#     weight = 4
